# Finds the Exactcolor software, by Stephan Held
# Sets:
# EXACTCOLORS_INCLUDE_DIR
# EXACTCOLORS_LIBRARY

CMAKE_MINIMUM_REQUIRED(VERSION 2.8.7 FATAL_ERROR)

INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(EXACTCOLORS_LIBRARY sewell HINTS "${EXACTCOLORS_ROOT_DIR}/lib")
FIND_PATH(EXACTCOLORS_INCLUDE_DIR "exactcolors/mwis_sewell/mwss_ext.h" HINTS "${EXACTCOLORS_ROOT_DIR}/include")

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Exactcolors
  REQUIRED_ARGS EXACTCOLORS_INCLUDE_DIR EXACTCOLORS_LIBRARY)